#!/bin/bash
####################################################################################################################################################################################

#Script Description:  clean up all the environments including fabric ,swift ,mysql 

#$1 ${installationPkgMountVolumeRoot}                       the root folder of the mount volume inside the tarball
#$2 ${installationPkgFabricArtifactsRoot}                   the root folder of the fabric artifacts generated by fabric tools inside the tarball
#$3 ${installationPkgSwiftStorageRoot}                      the root folder of the swift storage inside the tarball
#$4 ${installationPkgMySqlStorageRoot}                      the root folder of the mysql storage inside the tarball
#$5 ${installationPkgMySqlDBShellArtifactRoot}              the root folder of the db shell artifacts(replace the placeholder with actual dbUserName/dbPassword) inside the tarbal
#$6 ${installationPkgLogRoot}                               the root folder of logs
#$7 ${installationPkgApplicationArtifactsRoot}              the root folder of application artifacts
#$8 ${TFS_APPLICATION_PREFIX}                               the prefix of the application
#$9 ${TFS_API_APPLICATION_SHORT_NAME}                       the short name of the tfs-api application 
#$10 ${domainName}                                          the domain name of the fabric environment 
#$11 ${HOST_FILE}                                           the host file (/etc/hosts)
#$12 ${TFS_ADMIN_APPLICATION_SHORT_NAME}                    the short name of tfs-admin application
#$13 ${PROFILE}                                             /etc/profile
###################################################################################################################################################################################

# remove the fabric specified  host configurations from /etc/hosts file 
sed -i '/'"${10}"'/d' ${11} 

# remove the PATH env
#sed -i '/^NODE_HOME*/d'  ${13}
#sed -i '/^JAVA_HOME*/d'  ${13}
#sed -i '/^PATH*/d'  ${13}

# remove all the fabric containers ,search condition is to matchin the domain name of fabric env
docker-compose  -f  ${2}/docker-compose.yaml down 
docker rm -f $(docker ps -aq)
docker volume prune

# remove docker
sudo apt-get purge docker-ce
sudo rm -rf /var/lib/docker


# remove the tfs-api process
TFS_API_NAME=${8}-${9}
ps -ef | grep ${TFS_API_NAME} | grep -v "grep" | awk '{print $2}' | xargs kill -9

# remove the tfs-admin process
TFS_ADMIN_NAME=${8}-${12}
ps -ef | grep ${TFS_ADMIN_NAME} | grep -v "grep" | awk '{print $2}' | xargs kill -9

echo "remove all the mount volume sub-folders"
## remove all the mount volume sub-folders 
rm -rf  ${1}/*

echo "remove all the fabric artifacts generated by python"
## remove all the fabric artifacts generated by python
rm -rf  ${2}/*

echo "remove all the swift storage"
## remove all the swift storage
rm -rf  ${3}/*

echo "remove all the mysql storage"
## remove all the mysql storage
rm -rf  ${4}/*

echo "clean up the db shell artfacts folder"
## clean up the db shell artfacts folder 
rm -rf  ${5}/*

echo "clean up the log folder"
## clean up the log folder
rm -rf  ${6}/*

echo "clean up the log folder"
## clean up the application artifacts folder
rm -rf  ${7}/*



