#################################################################################################################################################

#Script Description:  generate network-config.yaml based on configuration parameters

#$1  ${installationPkgShellRoot}               the root folder the script scripts inside the tarball
#$2  ${installationPkgFabricArtifactsRoot}     the fabric artifact folder which is generated by fabric tools inside the tarball
#$3  ${orgCount}                               the number of the Organization
#$4  ${peerCountInOrg}                         the number of the peer in each organization
#$5  ${domainName}                             the domain name of the fabric network
#$6  ${registrarUserName}                      the registrar user name  for each CA in each organization
#$7  ${registrarUserPassword}                  the registrar user password for each CA in each organization
#$8  ${channelName}                            the name of the business channel

##################################################################################################################################################

python $1/config-fragments/network-config-generate.py  \
             --installationPkgFabricArtifactsRoot $2  \
             --orgCount $3 \
             --peerCountInOrg $4 \
             --domainName $5  \
             --registrarUserName $6  \
             --registrarUserPassword $7  \
             --channelName $8

