#!/bin/bash

################################################################################################################################################

#Script Description: generate the configtx.yaml using the configtx-generate.py based on the given parameters

#$1 ${installationPkgShellRoot}                    the root folder of shell scripts inside the tarball
#$2 ${installationPkgFabricArtifactsRoot}          the root folder of fabric artifacts generated by fabric tools inside the tarball
#$3 ${orgCount}                                    the number of Organizations 
#$4 ${kafkaCount}                                  the number of kafka brokers
#$5 ${ordererOrgName}                              the orderer organization name
#$6 ${domainName}                                  the domain name of the network
#$7 ${profilePrefixName}                           the prefix name of the profile 
#$8 ${consortiumName}                              the name of the consortium for the network


################################################################################################################################################

python  $1/config-fragments/configtx-generate.py  \
        --installationPkgFabricArtifactsRoot $2 \
        --orgCount $3 \
        --kafkaCount $4 \
        --ordererOrgName $5 \
        --domainName $6 \
        --profilePrefixName $7 \
        --consortiumName $8
